
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=yes&amp;characterEncoding=UTF-8"
    username: koung
    password: koung
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#
#        id:
#          new_generator_mappings: false
          
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data


#debug: true


server:
  port: 3000
